-- distances of less than 500 are strong candidates for being either the exact same entire file, or the exact same video.
-- although this is not guaranteed to be the case.
-- anything below 15000 i'd say gets close to being the same general primary color scheme. being generous.
-- at max distance, you tend to be purely looking at bright/white as a primary color vs dark/black between the two files.
select * from connection_data c
where c.source is not c.target
order by c.distance;

select * from connection_data c
where c.source is 'scr00066gondola2_1nRJN207E4MGRYhDof4pyw'
  and c.source is not c.target
order by c.distance;

-- these are true duplicates within the same category. It's reassuring to know there are so few i suppose.
-- these could be manually deleted in the future to keep the data pool clean.
select * from connection_data where distance is 0 and source is not target;

-- INTERESTING BITS --

-- pure black being registered is not very common, these are generally either fade ins or outs in the video.
select count(source), * from rgb_averages where b is 0 and g is 0 and r is 0 group by source;


-- DATA CLEANING --

-- import errors. should be fixed now, but keeping query for a bit.
delete from rgb_averages where source == 'source';

-- gondola corrupt files
delete from connection_data where source or target in
                                            (
                                             '103938572829_f8RLqj7FcbGoEoACIg',
                                             '1552719403032_n4oggPkQopZMim7FIOGMg',
                                             '1555396754211_MIcZvIJWSSW0cthNVIzi8A',
                                             '1572060457346_eiz0vDniuRuMdBibaR0LTw',
                                             '1573936335558_fi9CKXZrbdAvLTzanAtHw',
                                             '1580956430275_mgSWqAhsfRXiCHr2ZPEDA',
                                             '1582599764415_jFRKaFygYjShdmKzxaZ37g',
                                             '1585138120081_KewvktpJU8MAM59fPNruUQ',
                                             '1585705311528_DBHQ7qBDtz5UIwm3pRXANw',
                                             '1592518905357_mW5kG2xZRWnaOo6hfd0w',
                                             '1596828570404_wGq2VvHAkRn1TSXVe2NHg',
                                             '1599075795612_LPvAkH7uwZ80ZmmW1Iow',
                                             '1599092124580_YpPn2N0D7wu90BnSwV2qOA',
                                             '1599678451250_wljk52R5w42aJoqVtnEQQ',
                                             '1600341237889_MuIxshot1bf0gd3yLL2Cw',
                                             '1602015439723_tD6bMp6sNkQJsCsPFPjWA',
                                             '1602372890356_UqmcQohHLwQKxhLM4liuqg',
                                             '1602701658272_2JUua2vY01cvSiOQ5rSscw',
                                             '1602775534556_SD9pT6RoZE7fzII2BS9SiA',
                                             '1602863738778_tTDuUFZNowMBm9IxUgaI8g',
                                             '1605101159825_TMjBJcFCZtyOuOv4kVmGQ',
                                             '1608594765953_4qQYTKPi6OkpJSb6EbjpYw',
                                             '1Gondola2watch4change_t651KUCfCXBGlTzeFFLWmg',
                                             '456747_2FFJvPVZSNAtgrfS2FJLMw',
                                             '6435634_0gnizPd6bbDPEmWLDD1Zg',
                                             '8-SunnyDayRealEstate_egVUWgSZQRQloGYRIu3Fg',
                                             'ACGondola_BK2WxWAWCB9WO2GhYaVr9A',
                                             'ACourageGatheringGondola_0K4tUl3mM7AYnfBDJJw',
                                             'amaurot_MmsVNy9bAR4q9QXeRoMA5g',
                                             'AnAlpineLandscapewithaShepherdessandGondola_z1QItXrOHPt3d5zEQ5gfTA',
                                             'AndesGondola_AlRubztD1Iv7TG4PMSDnxw',
                                             'ants_anim_2_DNNtuq9SA6UcQhDBP0rg',
                                             'anunexpectedgondola39_DpBdB5PqVf5zAjk4qSX2Q',
                                             'AtTheGondolaOfItAll_a17Lg4Vz651893Fnwt9rqg',
                                             'B07_Vtz7JPcMA4HiVjPVQ5uXg',
                                             'b466e2d57a2a0a833414213d7b6c2ed8dfbe3ee0b33036cdfd43749b364d7504_b74OJRwNP1vacFRi1KBeEA',
                                             'bar_wBQHlwVvXPvCU3RfIzb2g',
                                             'believeme_y595OY02wIRpKr0q4TZ88g',
                                             'BirthdayGondola_ac1GCbtXBx88bR3kIhNwdA',
                                             'BliniGondola_dDFNGRGjFE81oz5EoQWng',
                                             'blueskiesgondola_eOO16fEDBbFUFXOUfvBU2w',
                                             'Bobby039sworld-Gondola_viR32raBtlMxWUuE3eFZ2A',
                                             'BrownEyedGondola-vanmorrison_jvCXTXNv3GNRGlvd7ejb7g',
                                             'cac8bb8a82c31b3a1906b7b0770464cebd6ea7ba47ae4ed69835a3f9412c4800_r9DwUFuKp6pit6S6Ifjlqg',
                                             'Capacities-Blue_Pzay7pl1zYi8xsdrqdwrzw',
                                             'CaptchDola_UeTLocAXRXRZQMQhSGdmg',
                                             'ChristBeWithMePlease_TAHLjcPPk1HaTE4cIFGew',
                                             'CivilWarGondola_mx1ddCRiw1uyeslYzgJgw',
                                             'comfy124gondola_0ZyfWMtNPJhPhTubl7LQ',
                                             'comfy172gondolaitaliansea_G4dYvk9fQudCzIfCFflkiQ',
                                             'comfy17_TXbuu5XjD3juwqn1ney7rw',
                                             'comfy307gondola_EhhoRSKCpg7bmD86bkQ',
                                             'comfy323gondola_ENJ71rT0lUBz9joBjt5kw',
                                             'comfy34_pDEYQ6luMSuK6itHoytdoQ',
                                             'controlgondola_4mT3819WTEA6p7ZoOyHA',
                                             'CrystalSnowGondola_n4rV2ROwnDKTosZThzFcA',
                                             'Day-to-dayGondola_4DfR6HGjm0GWLvwFimiqbA',
                                             'Day8_MbB8BtIRkwEyXf87jzxEQ',
                                             'DistantHorizons_Y39a4eNVtau4mGvRH5Yzug',
                                             'Fifth_Avenue_Stroll_Xeg3DBusMos0XkG7aezaA',
                                             'Ggar_8Ou3y2hLzevdAcKY1TpBw',
                                             'GondaHunter_i07LLkshQFRRDaagdJjNxQ',
                                             'GondGoandGondola_IlRc2XmkEBdwukqd4H4Q',
                                             'gondla2_VYpZKkjcx72gNxLbPhtnQ',
                                             'Gondola-HardspaceShipbreakerLaborofLove_3aYLS93khgk6J7FXMo7Q',
                                             'Gondola-on-hold_AKkAEW3JpJ81Xi1xEn4eig',
                                             'Gondola039sBasement_bRO8dx8zqr4Xm7EQfnw',
                                             'Gondola039sbirthdaylaps_7UUbZSwhi61V89a0oWzBA',
                                             'Gondola039sSleepParalysis_KyuCHkKJzERwriGQlVB5Sg',
                                             'gondola1_98bzCqyGawjECCCenegYQ',
                                             'gondola1_Ekj4nXy5iH0rEsbQmMHHaA',
                                             'gondolaabandoned_M9gs6rBrDe4gC2fuz3FA2w',
                                             'gondolaatrium_UdPOu5u1sSOPnpDgJQQKA',
                                             'gondolabaiotou_hBvKGaZ1Qn6Jo3motamtw',
                                             'gondolabar_ncULtamrxmj1AkTExTwvUQ',
                                             'GondolaBeach_PpPFd1dubmXvcDVPy7w',
                                             'gondolacarwash59_mXi5KUvJAuCjH5F5A16vCQ',
                                             'gondolacelebration_zP4k8MgdIB1NDgl4DZ6ug',
                                             'GondolaChaldaeaKitchen_HKWuqvM4OxEsZe5KGnrQw',
                                             'GondolaCity3_x104agZDzvpy4sSfAejgw',
                                             'gondolacommuting_XgHu7nlZGDyTBsaPiRTmg',
                                             'gondolacrosswalk_cRSRcEzqjoXfh27I5rjbA',
                                             'GondolaDesert2_4rxq1nCkH2Hfot2Ss2t4A',
                                             'gondoladonerkebab_faKsANd6DCuUBJA6w8Ww',
                                             'GondolaDoobyDo_5O6WMBavAbnkTS7UuxtglA',
                                             'gondoladreaming_xe85R21NlJuDDokcZ4IlQ',
                                             'gondolaearlybird_JHoHVlnorNOZKQoOIOcHA',
                                             'gondolaenjoying90sTV_3oIirSj2Bt2VcEwGjhvclg',
                                             'GondolaForever_vjQ5oGU0wGtL21O5rrlw',
                                             'gondolagang_nRca8qzLoTJj7gFcWHcN8g',
                                             'gondolagarage_4mHxjGUiAmxSvw5La2ni4w',
                                             'GondolaGreen_VEePUliuOHrcCRCNd0grkA',
                                             'gondolahibernia_NTpWIZq3fwxN89W8S5TuQg',
                                             'GondolaHomeward_92Cd2GKjk3283V8OppzBhw',
                                             'gondolahowth_ccggBSsG1QrKfeFqu1gyw',
                                             'GondolainRainWorld_eeE6QYwoqw6g2l0598Yo4w',
                                             'gondolainthesnow_F0BfMSpehnYVwzLSExwwQg',
                                             'GondolaIsFinallyFree_PGqTxW8PYSA6gOdKe62Dg',
                                             'Gondolaisnotrushing_98kMM8HcNjsFMQ0pwwhRIA',
                                             'gondolaizakaya_GiIy6X0r3nyiwZtw5gttwg',
                                             'gondolaizakaya_LEkoRjq84EdLHRY2deFw',
                                             'gondolakamchatka_zopgrgv9TdKirsid8oRSYQ',
                                             'gondolakiller_5P6qa3PSijEy91Ngf2G3nA',
                                             'gondolalaundromat_sctAAJmMIsA6pj3T5BfZQ',
                                             'Gondolamall_afJoDiBckTsd3GvVrkvaw',
                                             'GondolaMorning_1awyE1qaNCOJ0rC8PCjm8g',
                                             'GondolaMountainVillage_fcQEqsFE9SMhCW1K0tpGQ',
                                             'GondoLamp_qln45z2OdUVytSvTOjxWA',
                                             'Gondolanosun_bqGSqVl3WIuJAOoQkby4uA',
                                             'gondolaOC_USBmbSuHtiu6uer9UXjpng',
                                             'gondolaofbrokenness_F8XwLji2iQdVf61uv8JQ',
                                             'GondolaOfficerBritish_KhW6IXJ2zr050LeFu18EA',
                                             'GondolaOfTheLands_asoAtek27hl2GqfoRHjGA',
                                             'gondolaosake_58r4jmZNSmjSLMn557uIA',
                                             'GondolaRemembersHappierTimes_J3YeCyRe9Tm3O6hNZsUoEw',
                                             'gondolasnowstorm_VPb1xWlSQgVfiSLr2VBw',
                                             'Gondolasquare_I0Z8jsAcmmRf3hDvChGVA',
                                             'GondolaStranding_PMUlvV3uprQOXpPlFeHaEA',
                                             'gondolataishokissaten_HlAA9vpQ0ajCaeEPEpxqrg',
                                             'gondolatall_xFioHhvNlkINCf3dfosACA',
                                             'gondolatavern_wZ4a7mePXK8ZgQPsvlXStQ',
                                             'gondolawaitingforthetrain_wPbPDXGtMwKmaylcEDbqUQ',
                                             'Gondolawatchesoverus_w99qIWL0dN8z5Z8VhAApQ',
                                             'gondola_derelict_church_a4Pp2HCp5EwAWxNpLNk7mA',
                                             'gondola_hot_BN3B4QAShQPEN8HK0sRAg',
                                             'gondola_mario_kart_sPx2Y4q0i7tu4qF5vCtag',
                                             'gondola_sewers_Mpbqv5tQOjdEAIlzFi7EQQ',
                                             'Gondsauce_PydtnA9RWV7FJGnMiWwydg',
                                             'greenfields_lxDhnZkk7V4BkxwJFzmchg',
                                             'GrimFandangoGondola_ECYfqo0XqmhcXELgB0tUw',
                                             'happinessgondola_pkiGsWA58SJGjL230BJtkw',
                                             'HomeSweetGrave_ftYVCDv2xAIum8ZkHv5mg',
                                             'HudsonGondola_QyyP8cJwlHexiLUbguYITw',
                                             'idroidupgrade_PvqFDQExmE1ZDzcByRIV6w',
                                             'InallhisinfinitediversityGondola_aMICcCXbCjXxdDW6Xvag',
                                             'Interstellar_rRDahiWiCjq01bJfJN3aeg',
                                             'IrishWake-Keening_1RH45VG0xBUCu8iQ4optg',
                                             'Ispygondola1_TN8tE8IyH6NIHECTU3lrQ',
                                             'Ispygondola3_f1sYsAM0pVhGT1T9Rh3Tng',
                                             'Ispygondola4_9I2dJcKGQa67ggroUkn0IA',
                                             'IvanTorrent-BeforeILeaveThisWorld_4MDmHDX4R4LoQKX5BtIBQ',
                                             'Iwantyougondola_6j0enAXV9WpnMGDjWdAQ',
                                             'JamesPrimateSundownThemeIRainWorld_yR7AHWK9UAvyoAjf5tXmGQ',
                                             'jessiejames1_d3kbgppxqrDExuLdVCsew',
                                             'Kakkmaddafakka-SomeoneNewGondolaRemix_uOeC7LjOvNUBCe8Ki8QtaQ',
                                             'katawa_pUCUjJq58OLlAwnlDdqZCg',
                                             'KinkyBoots_CSBq7LJSBsAI1GXKzCy9w',
                                             'KirbyDola_6FJrYw2m4oXTIb59q2Q',
                                             'koadola_Zh7fzIznuOXwhFFJmYDYtA',
                                             'l432_ZaoJVpLUHSQHNRMWkRXiQ',
                                             'littleboxesgondola_PuoZR38yZoHRL4q99bxWBA',
                                             'mall_6y2pd5Tue3zD2DleLjmIA',
                                             'mcd039s_oNR2jdOlyPfdg4OS3gNg',
                                             'MedievalGondola_CrtdIyV6wduNHidaM863A',
                                             'miniature_gond_qYW52gD1UgLQI4JOy7ANrw',
                                             'mirror039sgond4_CCH5F55BSWCWaJ7TaKUVHg',
                                             'MirrorsEdgeGondola_wx8X1dvfVwvSh3jadLDn1w',
                                             'MPCGondola_TBv92pbwyLjNKivqeco1w',
                                             'NightclubGondola_MpAfg0U29ySCgvmWRDvGMA',
                                             'nomoreaffairs_xGfLH4tyjLUGpxdL6X98A',
                                             'Norman_Gondola_Em3CBJ3P4b5oWNbjqQgmQ',
                                             'Oberlord_Gondola_HdXEJUGudbF3yDzxVAadg',
                                             'OmnissiahGondola_Z78FfJfBNZLDlHSdCTNDQ',
                                             'OMyFather_bHQ5VDo4RQLtMoCefeo6dQ',
                                             'onagoodday_tJzJSYz86Sr13Tcpv4w',
                                             'Phoenix-Rome_sZnzwPLBPbGLW6USMDe3QQ',
                                             'PicturesofthePastIRainWorld_IWAsOxdBEp4aouuhTmyTsQ',
                                             'poorhonestgondola_qmNSt0Vhsi83uBXCS5ozMg',
                                             'Prelude_to_future_Gondola_meditation_peYliY4TmmKa8m2kxpUe4g',
                                             'Pumpkin_c8Cr2buwzdmOaz0NCxBW1Q',
                                             'QuintessenseWalterMitty_cLMUipXRtMzgPrxtLAOUQ',
                                             'reallife_EyD296DvPmG2KOBX5miZLQ',
                                             'redhotgondolaOC_WSxAehSr9VVgwtjzMSyYA',
                                             'retrogondola_9MRNAOkhZKLPXquFSBX9w',
                                             'retro_pc_home_MWT56kYVMq211jrFghN61g',
                                             'Sandcastle_Gondola_2_7eRlML6j3xs4cQiYol0RLg',
                                             'Sandcastle_Gondola_kQmBH4EvfSVYTIMlTITtnA',
                                             'SantaGondola_bW3LXPErwPO2EEGmKy0kjQ',
                                             'seacafe_gp5XEa3JY8W5kTJAJOUWMA',
                                             'ShojoA_UHUFo0dL5KRES9nUyaEJQ',
                                             'SnowGondola_RsLAlEg6Vzu5YSCbL4WoJw',
                                             'spacelaunchgondola_B7WaeTIBX5ISQsYDKumZ6Q',
                                             'spaceship_gi9PmUL8dqcB1WnKIB3gqA',
                                             'Spurdo_Space_Program_sP9CriniyGmPAimWdENmmA',
                                             'SSCraterGondola_znxHtsmHFxClCFj9LAujtw',
                                             'StargazingGondola_S0SsCINQNSgRHnkPgo95g',
                                             'stargazing_Sh6YOhH00xH7hJDAbnpHw',
                                             'staydeadcryptid_fV6CUE5G8dGpLnQfzlZRA',
                                             'Sun-treader_HWdi5PselaTawPJdXzqw',
                                             'TamaGe_dntIwNyw2NAQMhRfDgcjXQ',
                                             'TeatimeGondola_BzBYy2e4V5TnwCD4zdbA',
                                             'TechGondola_gjHheG39lZyIDOtgTRl7g',
                                             'teldrassilgondola_5jx2dieRttFkeN8lRgP5g',
                                             'TerryvsTori-HighTide_lA02igIvquTqHJzO6bNpg',
                                             'TestarossaViceGondolamellooooow_18BSwiObSzkkYCaAseTQ',
                                             'Theboxer_SSSTaP1wcYtXkEc7VLPsw',
                                             'TkmizTrainGondola_Xrem9O6RAD2RCZss6ZSg',
                                             'totemsofthegondolamaw_Tm3EBPRmSPGradAmzdLg',
                                             'Twilight_AECTzGp9oxElhIuASxppQg',
                                             'UminekoSeacat_Zi5yD3VQfqgybWFzFLY3XA',
                                             'UniverseGondola2_MixNeGaS57pPJZM8Mskghg',
                                             'universegondola_e0g8VPIbshtsTf9ld4a6A',
                                             'Valentines_zIu6qPHP21yMyfxToWW4A',
                                             'VikingTale_7lRn8ZnGWJPl5nCrE7sJWw',
                                             'wall_sSsCRH2PkTf0hqezPrexQ',
                                             'WatchingGondolaScum_04OrRUaqiOkLlFXHcxnErw',
                                             'whatwelost_BGrIPl8hm77OgCF5yq6Ag',
                                             'Wreck_of_the_Hesperus_-_Procol_Harum_lembRCBNrYkAuPf7ZALIg',
                                             'xyxy_wynuGkwOCI3TLbGjng',
                                             'YotsubaampGondola_V25OgJKfgsPggaInvOXqA'
                                                );

-- comfy corrupt files
delete from connection_data where source or target in
                                            (
                                             '1590023850722_W8ocZPokwNuIXCf6VdhuSA',
                                             '1593995600627_lrw7NYDyonpwCrskXEvYfQ',
                                             '1599438009216_lCBbnkCoLrQAJXzHPDWozw',
                                             '1606278254506_TG0h1ZoNUakypXf5YPx9g',
                                             'allnightergondola_bzkfYkzX737bx9T9agBVg',
                                             'asimpletraveler_6SpksMzXqGcj2R0Y6o5FwQ',
                                             'caption_this_T2YmxG1lbxR1RvMYNdiA',
                                             'comfy283gondolahoro_PfzgI5VhSLVSlX3DZFJLaQ',
                                             'comfypainting3_hHrSSS8FedAFLfG0bNgNNQ',
                                             'DjMallahfeatMcGauland-WIRWERDENSIEJAGEN_2qqpZ7uCCbquBG7dUe2Q',
                                             'DjMallahfeatMimonBaraka-BaldplatztdieBombebundesweit_iEKALIGadmq2jK13mpqlSQ',
                                             'FrhlingdringtindenNorden_pq7FtDWJ4IvWD5NyltdA',
                                             'IfZeewasagondola_99W6iFcGSXOvgz57HkKb2g',
                                             'Nostalgicmusic_uRtoJZ0pTCL9WLNtR20Iw',
                                             'pain_Ap9zaUVAjebIMe2tqcOXQ',
                                             'TerisLinar-Saberpunk_krTDn47N3MZN4g8Kkj9Vw',
                                             'themidnight-America2comfy_JbGO83PHN6ZBf1ndS7XUg',
                                             'twochendotmoeslashtv_uTv89GwnrskIBkKNhxvzWQ',
                                             'wc_2006_fVRaI9ZlcE7AjhFd97jdnw',
                                             'Winslow_Homer_-_An_Adirondack_Lake_iQ3Lto1X4yGtVkaPRec4Q',
                                             'yotsubawindows_86G3BLUuUeNOpKhRJumt0Q',
                                             'Yuunagi_Tut9P7ZSP6n2up8JxtPg'
                                                );
